server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL #MariaDB 쿼리 문법으로 작성하기 위해
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.hibernate.format_sql]': true
    show_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    '[project.jaeryang.bank]': DEBUG
